### ISSUE TITLE
Nawigacja

### ISSUE THREAD

**Issue by Qizot** [jmysliv/na-stok-app#2]
Wchodząc w wyjazdy, nie mając włączonej nawigacji, aplikacja powinna zrobić prompt o włączenie nawigacji oraz powwinień tam być refresh indicator by odświeżyć. Resetowanie apki z powodu braku lokalizacji jest bez sensu, włączenie lokalizacji oraz odświeżenie jest bardziej intuicyjne oraz nie wkukrwia.

**Comment by jmysliv** [comment]
Zaproponowane zmiany zostały wprowadzone w najnowszej wersji.
