### ISSUE TITLE
Ekran logowania

### ISSUE THREAD

**Issue by Qizot** [jmysliv/na-stok-app#3]
Przy nieprawidłowej próbie logowania, gdy jest wyświetlony czerwony snackbar z wiadomością o błędzie i się od razu wciśnie przycisk zaloguj to włącza się loading snackbar który niepotrzebnie jest pokazany przez cały jego duration time, jak się go przesunie w dół to od razu jest dostępny snackbar o błędzie. Jeśli backendowi to zapytanie nie zajmuje tyle czasu to czemu by nie od razu wyświetlić błędu zamiast czekać na schowanie się loadingu?

**Comment by jmysliv** [comment]
Błąd został naprawiony w najnowszej wersji.
