### ISSUE TITLE
UI ekarnu rejestracji

### ISSUE THREAD

**Issue by Qizot** [jmysliv/na-stok-app#4]
ListView powinno zajmować cały ekran a poszczególne widgety w nim powinny mieć własny padding żeby nie było widocznej poświaty jak na zdjęciu która jest tylko na części szerokości i nie zaczyna się od samej góry. Psuje to efekt wizualny

![87547983_2597842243833117_4770883375005171712_n](https://user-images.githubusercontent.com/34857220/75165319-7fa13f80-5722-11ea-9fbb-ca42f7788211.jpg)

**Comment by Qizot** [comment]
Dodatkowo podczas podania nieprawidłowego formatu oraz kolejnej próbie stworzenia konta nie wiadomo czy została wykonana kolejna próba i błąd został podświetlony jeszcze raz lub też do takiej próby nie doszło

**Comment by Qizot** [comment]
Dodatkkowo nie wysępuje limit znaków na nazwę użytkownika, przynajmniej takiej nie uświadczyłem

**Comment by jmysliv** [comment]
Wszystkie uwagi zostały uwzględnione i naprawione w najnowszej wersji.
