### ISSUE TITLE
UX tworzenie wyjazdu

### ISSUE THREAD

**Issue by Qizot** [jmysliv/na-stok-app#5]
Nie powinno tutaj byc floating action buttona tylko raised button na dole

![Screenshot_20200224-164039](https://user-images.githubusercontent.com/34857220/75166723-98aaf000-5724-11ea-8299-3f614da6edfb.jpg)

**Comment by Qizot** [comment]
Dodatkowo wybieranie sumy pieniędzy nie powinno być wertykalnym scrollem tylko input fieldem numerycznym

**Comment by Qizot** [comment]
Ten dialog nadaje sie do redesignu
![Screenshot_20200224-164641](https://user-images.githubusercontent.com/34857220/75167284-6948b300-5725-11ea-86c1-e9696b3cf05f.jpg)

**Comment by Qizot** [comment]
Dodatkowo po co tworzymy wyjazd za 2 lata, nostr adamus ze snieg bedzie?
![Screenshot_20200224-164951](https://user-images.githubusercontent.com/34857220/75167522-c7759600-5725-11ea-81d2-67d87343b914.jpg)

**Comment by Qizot** [comment]
Po co tutaj te sekundy
![Screenshot_20200224-165115](https://user-images.githubusercontent.com/34857220/75167618-f0962680-5725-11ea-9aea-25baffbdc06c.jpg)

**Comment by Qizot** [comment]
Przycisk cancel? 
![Screenshot_20200224-165243](https://user-images.githubusercontent.com/34857220/75167733-1e7b6b00-5726-11ea-9489-2dc239d530d5.jpg)

**Comment by jmysliv** [comment]
Jeśli chodzi o datę wyjazdu, to nie widzę przeszkód, by użytkownicy planowali wyjazdy z dwuletnim wyprzedzeniem, pozostałe uwagi bardzo cenne, zostały naprawione w najnowszej wersji.
