### ISSUE TITLE
Widok wyjazdu

### ISSUE THREAD

**Issue by Qizot** [jmysliv/na-stok-app#6]
Przy kliknięciu na nazwę stoku ładuje się jakiś nowy widok ale jest cały na szaro

**Comment by jmysliv** [comment]
Jest to błąd wynikający z błędu serwera, który w przyszłości nie powinien występować, jednak na wszelki wypadek, zostało to naprawione i w wypadku kolejnego takiego błędu, nie będzie można kliknąć w nazwę stoku i szary widok się nie wyświetli.
